"""URL definition for the beer site"""


from django.urls import path, include
from django.conf.urls import url
from beers.views import user, validation, contest, checkin
import beers.api.views as api_views

api_patterns = [
    path('players/', api_views.PlayerList.as_view(), name='player-list',),
    path('players/<slug:user__username>', api_views.PlayerDetail.as_view(), name='player-detail',),
    path('contests/', api_views.ContestList.as_view(), name='contest-list',),
    path('contests/<int:id>', api_views.ContestDetail.as_view(), name='contest-detail',),
    path('contests/<int:contest_id>/players/', 
         api_views.ContestPlayerList.as_view(), 
         name='contest-player-list',),
    path('contests/<int:contest_id>/players/<slug:username>',
         api_views.ContestPlayerDetail.as_view(),
         name='contest-player-detail',),
    path('contests/<int:contest_id>/beers/', 
         api_views.ContestBeerList.as_view(), 
         name='contest-beer-list',),
    path('contests/<int:contest_id>/beers/<int:contest_beer_id>',
         api_views.ContestBeerDetail.as_view(),
         name='contest-beer-detail',),
    path('contests/<int:contest_id>/breweries/',
         api_views.ContestBreweryList.as_view(),
         name='contest-brewery-list',),
    path('contests/<int:contest_id>/breweries/<int:contest_brewery_id>',
         api_views.ContestBreweryDetail.as_view(),
         name='contest-brewery-detail',),
    path('contests/<int:contest_id>/bonuses',
         api_views.ContestBonusList.as_view(),
         name='contest-bonus-list',),
    path('contests/<int:contest_id>/bonuses/<int:contest_bonus_id>',
         api_views.ContestBonusDetail.as_view(),
         name='contest-bonus-detail',),
    path('contests/<int:contest_id>/unvalidated_checkins',
         api_views.UnvalidatedCheckinList.as_view(),
         name='unvalidated-checkin-list',),
    path('unvalidated_checkins/<int:id>',
         api_views.UnvalidatedCheckinDetail.as_view(),
         name='unvalidated-checkin-detail',),
    path('lookup/beer', api_views.BeerLookup.as_view(), name='beer-lookup'),
    path('lookup/brewery', api_views.BreweryLookup.as_view(), name='brewery-lookup'),
]

urlpatterns = [
    url(r'^$', contest.index, name='index'),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^signup$', user.signup, name='signup'),
    url(r'^profile', user.update_profile, name='profile'),
    url(r'^contests/$', contest.contests, name='contests'),
    url(r'^contests/add$', contest.contest_add, name='contest-add'),
    url(r'^contests/(?P<contest_id>[0-9]+)/$',
        contest.contest,
        name='contest'),
    url(r'^contests/(?P<contest_id>[0-9]+)/join$',
        contest.contest_join,
        name='contest-join'),
    url(r'^contests/(?P<contest_id>[0-9]+)/validate$',
        validation.unvalidated_checkins,
        name='unvalidated-checkins'),
    url(r'^contests/(?P<contest_id>[0-9]+)/unvalidated_checkins$',
        validation.unvalidated_checkins_json,
        name='unvalidated-checkins-json'),
    url(r'^contests/(?P<contest_id>[0-9]+)/unvalidated_checkins/(?P<uv_checkin>[0-9]+)$',
        validation.delete_checkin,
        name='delete-checkin'),
    url(r'^contests/(?P<contest_id>[0-9]+)/checkins$',
        validation.validate_checkin,
        name='validate-checkin'),
    url(r'^contests/(?P<contest_id>[0-9]+)/players/(?P<username>[^/]+)$',
        contest.contest_player,
        name='contest-player'),
    url(r'^contests/(?P<contest_id>[0-9]+)/players/$',
        contest.contest_players,
        name='contest-players'),
    url(r'^contests/(?P<contest_id>[0-9]+)/beers/(?P<beer_id>[0-9]+)$',
        contest.contest_beer,
        name='contest-beer'),
    url(r'^contests/(?P<contest_id>[0-9]+)/beers/$',
        contest.contest_beers,
        name='contest-beers'),
    url(r'^contests/(?P<contest_id>[0-9]+)/breweries/$',
        contest.contest_breweries,
        name='contest-breweries'),
    url(r'^contests/(?P<contest_id>[0-9]+)/breweries/(?P<brewery_id>[0-9]+)$',
        contest.contest_brewery,
        name='contest-brewery'),
    url(r'^contests/(?P<contest_id>[0-9]+)/challenges/(?P<beer_id>[0-9]+)$',
        contest.contest_challenge,
        name='contest-challenge'),
    url(r'^contests/(?P<contest_id>[0-9]+)/challenges/$',
        contest.contest_challenges,
        name='contest-challenges'),
    url(r'^contests/(?P<contest_id>[0-9]+)/bonuses/$',
        contest.contest_bonuses,
        name='contest-bonuses'),
    url(r'^contests/(?P<contest_id>[0-9]+)/bonuses/(?P<bonus_tag>[A-Za-z0-9]+)$',
        contest.contest_bonus,
        name='contest-bonus'),
    # url(r'^contests/(?P<contest_id>[0-9]+)/unvalidated_checkins$',
        # checkin.add_unvalidated_checkin,
        # name='add-unvalidated-checkin'),
    url(r'^instructions$', contest.instructions, name='instructions'),
    path('api', include(api_patterns)),
]
