# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0003_auto_20151225_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='beers.Player'),
        ),
    ]
