# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0005_contest_player_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='brewery_city',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='brewery_country',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='brewery_state',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
