# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0006_auto_20151230_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='runner_validated',
            field=models.BooleanField(default=False),
        ),
    ]
