# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0007_checkin_runner_validated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unvalidated_Checkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('untappd_title', models.CharField(max_length=500)),
                ('untappd_checkin', models.URLField()),
                ('untappd_checkin_date', models.DateTimeField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beers.Player')),
            ],
        ),
    ]
