# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0008_unvalidated_checkin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unvalidated_checkin',
            name='player',
        ),
        migrations.AddField(
            model_name='unvalidated_checkin',
            name='contest_player',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='beers.Contest_Player'),
            preserve_default=False,
        ),
    ]
