# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0009_auto_20151230_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='unvalidated_checkin',
            name='beer',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='unvalidated_checkin',
            name='brewery',
            field=models.CharField(default='', max_length=250),
        ),
    ]
