# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0011_auto_20160110_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='untappd_username',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
