# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 03:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0013_contest_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest_player',
            name='last_checkin_load_start',
            field=models.DateTimeField(default=datetime.datetime(2015, 1, 1, 0, 0, 0, tzinfo=datetime.timezone(datetime.timedelta(hours=-5))), verbose_name=''),
            preserve_default=False,
        ),
    ]
