# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-23 21:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0014_contest_player_last_checkin_load_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest_player',
            name='last_checkin_load_start',
        ),
        migrations.AddField(
            model_name='contest_player',
            name='last_checkin_load',
            field=models.DateTimeField(default=datetime.datetime(2014, 1, 1, 0, 0, tzinfo=datetime.timezone(datetime.timedelta(hours=-5))), verbose_name='Latest date in the last load for this player'),
            preserve_default=False,
        ),
    ]
