# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0016_auto_20170423_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest_checkin',
            name='checkin_points',
            field=models.IntegerField(default=1),
        ),
    ]
