# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0019_auto_20170617_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest_beer',
            name='challenge_point_loss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contest_beer',
            name='challenge_point_value',
            field=models.IntegerField(default=0, help_text='The number of points a challenger gets for drinking this beer'),
        ),
        migrations.AddField(
            model_name='contest_beer',
            name='challenger',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='beers.Contest_Player'),
        ),
        migrations.AddField(
            model_name='contest_beer',
            name='max_point_loss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contest_player',
            name='challenge_point_gain',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contest_player',
            name='challenge_point_loss',
            field=models.IntegerField(default=0),
        ),
    ]
