# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-17 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0020_auto_20170704_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest_beer',
            name='challenge_point_value',
            field=models.IntegerField(default=0, help_text='The number of points the challenger gets for drinking this beer'),
        ),
        migrations.AlterField(
            model_name='contest_brewery',
            name='total_visited',
            field=models.IntegerField(default=0, help_text='number of players who drank at this brewery'),
        ),
    ]
