# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-18 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0021_auto_20171117_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest_checkin',
            name='bonus_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contest_checkin',
            name='tx_type',
            field=models.CharField(choices=[('BE', 'Beer'), ('BR', 'Brewery'), ('CB', 'Challenge Beer'), ('CL', 'Challenge Beer Loss'), ('BO', 'Bonus')], default='BE', max_length=2),
        ),
    ]
