# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-26 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0024_auto_20171117_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest_player',
            name='bonus_points',
            field=models.IntegerField(default=0),
        ),
    ]
