# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-07 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0025_contest_player_bonus_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='untappd_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
