# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-07 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0027_auto_20180107_0959'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contest_beer',
            unique_together=set([('contest', 'beer')]),
        ),
    ]
