# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-11 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0028_auto_20180107_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='brewery_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brewery',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='unvalidated_checkin',
            name='beer_url',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='unvalidated_checkin',
            name='brewery_url',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='unvalidated_checkin',
            name='photo_url',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='unvalidated_checkin',
            name='rating',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
