# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-18 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0029_auto_20180211_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='beer',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='player',
        ),
        migrations.DeleteModel(
            name='Checkin',
        ),
    ]
