# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-19 03:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0031_auto_20180218_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest_player',
            name='rank',
        ),
    ]
