# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-05 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0034_auto_20180422_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest_beer',
            name='brewery_name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
