# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0037_contest_bonus_hashtags'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE beers_contest_bonus SET hashtags = string_to_array(hash_tags, ',')",
            "UPDATE beers_contest_bonus SET hashtags = NULL")
    ]
