# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0038_auto_20180506_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest_bonus',
            name='hash_tags',
        ),
    ]
