# Generated by Django 2.2 on 2019-04-08 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0039_remove_contest_bonus_hash_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='beers.Player'),
        ),
    ]
